Task/School/School/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Task/School/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/',views.login, name='login'),
    path('signup/',views.signup, name='signup'),
    path('studentsignup/',views.studentsignup, name='studentsignup'),
    path('teachersignup/',views.teachersignup, name='teachersignup'),
    path('studentdashboard/',views.studentdashboard, name='studentdashboard'),
    path('teacherdashboard/',views.teacherdashboard, name='teacherdashboard'),
    path('studentlogin/',views.studentlogin, name='studentlogin'),
    path('teacherlogin/',views.teacherlogin, name='teacherlogin'),
    path('admindashboard/',views.admindashboard, name='admindashboard'),
    path('photo/',views.photo, name='photo'),
    path('studentphoto/',views.studentphoto, name='studentphoto'),
    path('teacherphoto/',views.teacherphoto, name='teacherphoto'),
    
]

Task/School/home/models.py
from django.db import models

class user(models.Model):
    username=models.CharField(max_length=50)
    email=models.EmailField(max_length=50)
    phoneno=models.CharField(max_length=10)
    password=models.CharField(max_length=500)
    is_active=models.BooleanField(default=True)
    # image=models.ImageField(upload_to='photo')
    def __str__(self) -> str:
        return self.username

class student(models.Model):
    sname=models.CharField(max_length=50)
    email=models.EmailField(max_length=50)
    phoneno=models.CharField(max_length=10)
    password=models.CharField(max_length=500)
    image=models.ImageField(upload_to='media')
    def __str__(self) -> str:
        return self.sname
    
class teacher(models.Model):
    tname=models.CharField(max_length=50)
    email=models.EmailField(max_length=50)
    phoneno=models.CharField(max_length=10)
    password=models.CharField(max_length=500) 
    image=models.ImageField(upload_to='pics')
    def __str__(self) -> str:
        return self.tname


class Image(models.Model):
 photo = models.ImageField(upload_to="myimage")
 date = models.DateTimeField(auto_now_add=True)


class StudentImage(models.Model):
 photo = models.ImageField(upload_to="myphoto")
 date = models.DateTimeField(auto_now_add=True)
 

class TeacherImage(models.Model):
 photo = models.ImageField(upload_to="mypic")
 date = models.DateTimeField(auto_now_add=True)

Task/School/home/forms.py
from django import forms
from .models import Image,StudentImage,TeacherImage

class ImageForm(forms.ModelForm):
 class Meta:
  model = Image
  fields = '__all__'
  labels = {'photo':''}
  
class StudentForm(forms.ModelForm):
 class Meta:
  model = StudentImage
  fields = '__all__'
  labels = {'photo':''}
  

class TeacherForm(forms.ModelForm):
 class Meta:
  model = TeacherImage
  fields = '__all__'
  labels = {'photo':''}

Task/School/home/views.py
from django.shortcuts import render,redirect
from home.models import user,student,teacher,Image,StudentImage,TeacherImage
from django.contrib.auth.hashers import make_password,check_password
from django.http import HttpResponse
from .forms import ImageForm,StudentForm,TeacherForm

# Create your views here.
def home(request):
    return render(request, 'dashboard.html')

def admindashboard(request):
    return render(request, 'admindashboard.html')

def login(request):
    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']
        if user.objects.filter(email=email).exists():
            s=user.objects.get(email=email)
            pwd=s.password
            if check_password(password,pwd):
                return redirect('/admindashboard')
            else:
                return redirect('/login')
            
        else:
            return redirect('/signup')
            
    else:
        return render(request, 'login.html')

def studentlogin(request):
    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']
        if student.objects.filter(email=email).exists():
            s=student.objects.get(email=email)
            pwd=s.password
            if check_password(password,pwd):
                return redirect('/studentdashboard')
            else:
                return redirect('/studentlogin')
            
        else:
            return redirect('/studentlogin')
           
    else:
        return render(request, 'studentlogin.html')
    
def teacherlogin(request):
    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']
        if teacher.objects.filter(email=email).exists():
            s=teacher.objects.get(email=email)
            pwd=s.password
            if check_password(password,pwd):
                return redirect('/teacherdashboard')
            else:
                return redirect('/login')
            
        else:
            return redirect('/teachersignup')
            
    else:
        return render(request, 'teacherlogin.html')

def signup(request):
    if request.method=='POST':
        username = request.POST['username']
        email = request.POST['email']
        phoneno=request.POST['number']
        password=make_password(request.POST['password'])
        if user.objects.filter(email=email).exists():
            return redirect('/signup')
        else:
            user.objects.create(username=username,email=email,phoneno=phoneno,password=password)
            return redirect('/login')
    return render(request, 'signup.html')

def studentsignup(request):
    if request.method=='POST':
        username = request.POST['username']
        email = request.POST['email']
        phoneno=request.POST['number']
        password=make_password(request.POST['password'])
        if student.objects.filter(email=email).exists():
            return redirect('/signup')
        else:
            student.objects.create(sname=username,email=email,phoneno=phoneno,password=password)
            return redirect('/studentlogin')
    return render(request, 'studentsignup.html')

def teachersignup(request):
    if request.method=='POST':
        username = request.POST['username']
        email = request.POST['email']
        phoneno=request.POST['number']
        password=make_password(request.POST['password'])
        if teacher.objects.filter(email=email).exists():
            return redirect('/signup')
        else:
            teacher.objects.create(tname=username,email=email,phoneno=phoneno,password=password)
            return redirect('/teacherlogin')
    return render(request, 'teachersignup.html')

def studentdashboard(request):
    return render(request, 'studentdashboard.html')

def teacherdashboard(request):
    return render(request, 'teacherdashboard.html')


def photo(request):
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        form = ImageForm()
        img = Image.objects.all()
        stu= StudentImage.objects.all()
        tea=TeacherImage.objects.all()
        return render(request, 'admindashboard.html', {'img':img,'stu':stu,'tea':tea, 'form':form})
    else:
        form = ImageForm()
        img = Image.objects.all()
        stu= StudentImage.objects.all()
        tea=TeacherImage.objects.all()
        return render(request, 'admindashboard.html', {'img':img,'stu':stu,'tea':tea, 'form':form})

def studentphoto(request):
    if request.method == "POST":
        form= StudentForm(data=request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
        form=StudentForm()
        img=StudentImage.objects.all()
        return render(request, "studentdashboard.html",{"img":img, "form":form})
    else:
        form=StudentForm()
        img=StudentImage.objects.all()
        return render(request, "studentdashboard.html",{"img":img, "form":form})
    
def teacherphoto(request):
    if request.method == "POST":
        form = TeacherForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        form = TeacherForm()
        pic = TeacherImage.objects.all()
        stu= StudentImage.objects.all()
        return render(request, 'teacherdashboard.html', {'pic': pic, 'stu':stu, 'form':form})
    else:
        form = TeacherForm()
        pic = TeacherImage.objects.all()
        stu= StudentImage.objects.all()
        return render(request, 'teacherdashboard.html', {'pic': pic, 'stu':stu, 'form':form})

Task/School/home/templates/admindashboard.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Image Uploader</title>
    <style>
      * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    
    body {
      font-family: sans-serif;
      font-size: 16px;
      line-height: 2.5;
      color: black;
      background-color: #EDDEF1;
    }
    
    header {
      background-color: #E3E5F6;
      padding: 30px;
      box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.1);
    }
    
    header h1 {
      margin: 0;
      font-size: 38px;
    }
    
    nav {
      float: right;
      font-size: 18px;
      color: #44254C;
    }
    
    nav ul {
      list-style: none;
      margin: 0;
      padding: 10;
    }
    
    nav li {
      display: inline-block;
      margin-left: 20px;
    }
    
    nav a {
      color: #44254C;
      text-decoration: none;
      padding: 5px 10px;
    }
    
  </style>
    
  </head>
  <body>
    <header>
      <div class="container">
        <h1>Welcome to Admin Dashboard Page</h1>
      </div>
    </header>
    
   <div class="container">
    <div class="py-5 text-center bg-dark text-white">
     <h1 class="mb-3">Upload Image</h1>
     <form action="{% url 'photo'%}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form}}<br>
      {% comment %} <input type="file" name="photo" accept="image/*" required="" id="id_photo"> {% endcomment %}
      <input type="submit" class="btn btn-outline-danger" value="Upload">
    </div></br>
    <center><h1>Admin Images</h1></center>
    <div class="row">
     {% for x in img %}
      <div class="col-sm-4">
       <div class="card m-2">
        <img src="{{x.photo.url}}" alt="" class="card-img-top" height="200px">
        <div class="card-footer">
         <small class="text-muted">{{x.date}}</small>
        </div>
       </div>
      </div>
     {% endfor %}
    </div>
    <hr/>
    <div class="container">
      <center><h1>Student Images</h1></center>
      <div class="row">
        {% for y in stu %}
         <div class="col-sm-4">
          <div class="card m-2">
           <img src="{{y.photo.url}}" alt="" class="card-img-top" height="200px">
           <div class="card-footer">
            <small class="text-muted">{{y.date}}</small>
           </div>
          </div>
         </div>
        {% endfor %}
       </div>
    </div>
    <hr/>
    <div class="container">
      <center><h1>Teacher Images</h1></center>
      <div class="row">
        {% for z in tea %}
         <div class="col-sm-4">
          <div class="card m-2">
           <img src="{{z.photo.url}}" alt="" class="card-img-top" height="200px">
           <div class="card-footer">
            <small class="text-muted">{{z.date}}</small>
           </div>
          </div>
         </div>
        {% endfor %}
       </div>
    </div>

   </div>
  </form>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

Task/School/home/templates/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Landing Page</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Add Bootstrap CSS link here -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- Add custom CSS styles here -->
    <style>
      /* Custom CSS styles go here */
      body {
        font-family: 'Montserrat', sans-serif;
        background-color: #F5ECF7;
      }
      .jumbotron {
        background-color: #E3E3F3;
        padding-top: 5rem;
        padding-bottom: 5rem;
        text-align: center;
        margin-bottom: 0;
      }
      .jumbotron h1 {
        font-size: 4rem;
        font-weight: bold;
        margin-bottom: 2rem;
      }
      .jumbotron p {
        font-size: 1.5rem;
        margin-bottom: 2rem;
      }
      .btn-primary {
        font-size: 1.5rem;
        padding: 1rem 2rem;
        border-radius: 2rem;
      }
      .features {
        background-color: #F5ECF7;
        padding-top: 5rem;
        padding-bottom: 5rem;
        text-align: center;
      }
      .features h2 {
        font-size: 3rem;
        font-weight: bold;
        margin-bottom: 2rem;
      }
      .features p {
        font-size: 1.5rem;
        margin-bottom: 2rem;
      }
      .feature {
        margin-bottom: 3rem;
      }
      .feature h3 {
        font-size: 2rem;
        font-weight: bold;
        margin-bottom: 1rem;
      }
      .feature p {
        font-size: 1.2rem;
      }
      .footer {
        background-color: #333;
        color: #5A1A6A;
        padding: 3rem 0;
        text-align: center;
      }
      .footer p {
        font-size: 1.2rem;
        margin-bottom: 0;
      }
    </style>
  </head>
  <body>
    <div class="jumbotron">
      <div class="container">
        <h1>Welcome to Dashboard</h1>
        <p class="lead">All details of Admin, Student, Teacher related courses</p>
        <a href="{% url 'signup' %}" class="btn btn-primary">Admin</a>
        <a href="{% url 'studentsignup' %}" class="btn btn-primary">Student</a>
        <a href="{% url 'teachersignup' %}" class="btn btn-primary">Teacher</a>
        </div>
    </div>
    
    <div class="features">
      <div class="container" style="color:#180E56">
        <h2>Our Features</h2>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        <div class="row">
          <div class="col-md-4" style="color:#180E56">
            <div class="feature">
              <h3>Admin Feature</h3>
              <h4>Admin Feature is to access all images of Student and Teacher</h4>
            </div>
          </div>
          <div class="col-md-4" style="color:#180E56">
            <div class="feature">
              <h3>Student Feature</h3>
              <h4>Student Feature is to add images and courses</h4>
            </div>
		  </div>
		  <div class="col-md-4" style="color:#180E56">
            <div class="feature">
              <h3>Teacher Feature</h3>
              <h4>Teacher Feature is to access images of Student and Self images</h4>
            </div>
          </div>
        </div>
	 </div>
    </div>

Task/School/home/templates/login.html
<!DOCTYPE html>
<html>
<head>
  <title>Login Page</title>
  <link rel="stylesheet" type="text/css" href="style.css">
<style>
  body {
    background: #d9d9d9;
    font-family: sans-serif;
  }

.login-box {
    width: 280px;
    height: 380px;
    background: #ffffff;
    color: #000000;
    top: 50%;
    left: 50%;
    position: absolute;
    transform: translate(-50%, -50%);
    box-sizing: border-box;
    padding: 70px 30px;
  }

.avatar {
    width: 100px;
    height: 100px;
    border-radius: 50%;
    position: absolute;
    top: -50px;
    left: calc(50% - 50px);
  }

h1 {
    margin: 0;
    padding: 0 0 20px;
    text-align: center;
    font-size: 22px;
  }

.login-box p {
    margin: 0;
    padding: 0;
    font-weight: bold;
  }

.login-box input {
    width: 100%;
    margin-bottom: 20px;
  }

.login-box input[type="text"],
.login-box input[type="password"] {
    border: none;
    border-bottom: 1px solid #000000;
    background: transparent;
    outline: none;
    height: 40px;
    color: #000000;
    font-size: 16px;
  }

.login-box input[type="submit"] {
    border: none;
    outline: none;
    height: 40px;
    background: #000000;
    color: #ffffff;
    font-size: 18px;
    border-radius: 20px;
  }

.login-box input[type="submit"]:hover {
    cursor: pointer;
    background: #2ecc71;
    color: #ffffff;
  }
</style>
</head>
<body>
  <div class="login-box">
    <img src="user.png" class="avatar">
    <h1>Login Here</h1>
    <form action="/login/" method="post">
      {% csrf_token %}
	  <p>Email</p>
	  <input type="text" class="form-control" id="email" name="email" placeholder="Enter email" required>
      <p>Password</p>
      <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
      <input type="submit" name="submit" value="Login">
    </form>
    <div class="card-footer text-center">
            <a href="#">Forgot password?</a>
    </div>
  </div>
</body>
</html>

Task/School/home/templates/signup.html

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Sign Up</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css">
</head>
<body>
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-6">
				<div class="card">
					<div class="card-header">
						<h4 class="card-title">Sign Up</h4>
					</div>
					<div class="card-body">
						<form action="/signup/" method="POST">
						{% csrf_token %}
							<div class="mb-3">
								<label for="username" class="form-label"></label>
								<input type="text" class="form-control" name="username" placeholder="Username" required>
							</div>
							<div class="mb-3">
								<label for="email" class="form-label"></label>
								<input type="email" class="form-control" name="email" placeholder="Email" required>
							</div>
							<div class="mb-3">
								<label for="number" class="form-label"></label>
								<input type="text" class="form-control" name="number" placeholder="Phone Number" required>
							</div>
							
							<div class="mb-3">
								<label for="password" class="form-label"></label>
								<input type="password" class="form-control" name="password" placeholder="Password" required>
							</div>
							<div class="d-grid">
								<button type="submit" class="btn btn-primary">Sign Up</button>
							</div>
						
							
						</form>
						<div class="card-footer text-center pt-0 px-lg-2 px-1">
							<p class="mb-2 text-sm mx-auto">
							  Already have an account?
							  <a href="{% url 'login' %}" class="text-primary text-gradient font-weight-bold"><button class="btn btn-outline-danger">Login</button></a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"></script>
</body>
</html>

Task/School/home/templates/studentdashboard.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Image Uploader</title>
    <style>
      * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    
    body {
      font-family: sans-serif;
      font-size: 16px;
      line-height: 2.5;
      color: black;
      background-color: #EDDEF1;
    }
    
    header {
      background-color: #E3E5F6;
      padding: 30px;
      box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.1);
    }
    
    header h1 {
      margin: 0;
      font-size: 38px;
    }
    
    nav {
      float: right;
      font-size: 18px;
      color: #44254C;
    }
    
    nav ul {
      list-style: none;
      margin: 0;
      padding: 10;
    }
    
    nav li {
      display: inline-block;
      margin-left: 20px;
    }
    
    nav a {
      color: #44254C;
      text-decoration: none;
      padding: 5px 10px;
    }
    
  </style>
    
  </head>
  <body>
    <header>
      <div class="container">
        <h1>Welcome to Student Dashboard Page</h1>
      </div>
    </header>
    
   <div class="container">
    <div class="py-5 text-center bg-dark text-white">
     <h1 class="mb-3">Upload Image</h1>
     <form action="{% url 'studentphoto' %}" method="post" enctype="multipart/form-data">
     {% csrf_token %}
      {{form}}<br>
      {% comment %} <input type="file" name="photo" accept="image/*" required="" id="id_photo"> {% endcomment %}
      <input type="submit" class="btn btn-outline-danger" value="Upload">
    </div>
    <div class="row">
     {% for x in img %}
      <div class="col-sm-4">
       <div class="card m-2">
        <img src="{{x.photo.url}}" alt="" class="card-img-top" height="200px">
        <div class="card-footer">
         <small class="text-muted">{{x.date}}</small>
         <h1>{{x.sname}}</h1>
        </div>
       </div>
      </div>
     {% endfor %}
    </div>
   </div>
  </form>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

Task/School/home/templates/studentlogin.html
<!DOCTYPE html>
<html>
<head>
  <title>Login Page</title>
  <link rel="stylesheet" type="text/css" href="style.css">
<style>
  body {
    background: #d9d9d9;
    font-family: sans-serif;
  }

.login-box {
    width: 280px;
    height: 380px;
    background: #ffffff;
    color: #000000;
    top: 50%;
    left: 50%;
    position: absolute;
    transform: translate(-50%, -50%);
    box-sizing: border-box;
    padding: 70px 30px;
  }

.avatar {
    width: 100px;
    height: 100px;
    border-radius: 50%;
    position: absolute;
    top: -50px;
    left: calc(50% - 50px);
  }

h1 {
    margin: 0;
    padding: 0 0 20px;
    text-align: center;
    font-size: 22px;
  }

.login-box p {
    margin: 0;
    padding: 0;
    font-weight: bold;
  }

.login-box input {
    width: 100%;
    margin-bottom: 20px;
  }

.login-box input[type="text"],
.login-box input[type="password"] {
    border: none;
    border-bottom: 1px solid #000000;
    background: transparent;
    outline: none;
    height: 40px;
    color: #000000;
    font-size: 16px;
  }

.login-box input[type="submit"] {
    border: none;
    outline: none;
    height: 40px;
    background: #000000;
    color: #ffffff;
    font-size: 18px;
    border-radius: 20px;
  }

.login-box input[type="submit"]:hover {
    cursor: pointer;
    background: #2ecc71;
    color: #ffffff;
  }
</style>
</head>
<body>
  <div class="login-box">
    <img src="user.png" class="avatar">
    <h1>Login Here</h1>
    <form action="/studentlogin/" method="post">
	  {% csrf_token %}
	  <p>Email</p>
	  <input type="text" class="form-control" id="email" name="email" placeholder="Enter email" required>
      <p>Password</p>
      <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
      <input type="submit" name="submit" value="Login">
    </form>
    <div class="card-footer text-center">
            <a href="#">Forgot password?</a>
    </div>
  </div>
</body>
</html>

Task/School/home/templates/teacherdashboard.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Image Uploader</title>
    <style>
      * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }
    
    body {
      font-family: sans-serif;
      font-size: 16px;
      line-height: 2.5;
      color: black;
      background-color: #EDDEF1;
    }
    
    header {
      background-color: #E3E5F6;
      padding: 30px;
      box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.1);
    }
    
    header h1 {
      margin: 0;
      font-size: 38px;
    }
    
    nav {
      float: right;
      font-size: 18px;
      color: #44254C;
    }
    
    nav ul {
      list-style: none;
      margin: 0;
      padding: 10;
    }
    
    nav li {
      display: inline-block;
      margin-left: 20px;
    }
    
    nav a {
      color: #44254C;
      text-decoration: none;
      padding: 5px 10px;
    }
    
  </style>
    
  </head>
  <body>
    <header>
      <div class="container">
        <h1>Welcome to Teacher Dashboard Page</h1>
      </div>
    </header>
    
   <div class="container">
    <div class="py-5 text-center bg-dark text-white">
     <h1 class="mb-3">Upload Image</h1>
     <form action="{% url 'teacherphoto' %}" method="post" enctype="multipart/form-data">
     {% csrf_token %}
      {{form}}<br>
      {% comment %} <input type="file" name="photo" accept="image/*" required="" id="id_photo"> {% endcomment %}
      <input type="submit" class="btn btn-outline-danger" value="Upload">
    </div></br>
    <center><h1>Teacher Images</h1></center>
    <div class="row">
     {% for x in pic %}
      <div class="col-sm-4">
       <div class="card m-2">
        <img src="{{x.photo.url}}" alt="" class="card-img-top" height="200px">
        <div class="card-footer">
         <small class="text-muted">{{x.date}}</small>
        </div>
       </div>
      </div>
     {% endfor %}
    </div>
    <hr/>
    <div class="container">
      <center><h1>Student Images</h1></center>
      <div class="row">
        {% for y in stu %}
         <div class="col-sm-4">
          <div class="card m-2">
           <img src="{{y.photo.url}}" alt="" class="card-img-top" height="200px">
           <div class="card-footer">
            <small class="text-muted">{{y.date}}</small>
           </div>
          </div>
         </div>
        {% endfor %}
       </div>
    </div>
   </div>
  </form>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>